web_package: apache2
phpinfo_dir: /srv/www/htdocs/phpinfo.php
php_package:
  - libapache2-mod-php
  - w3m
  - apache2
  - apache2-mod_dnssd
  - apache2-prefork
  - libgc1
  - php7-ctype
  - php7-dom
  - php7-iconv
  - php7-json
  - php7-sqlite
  - php7-tokenizer
  - php7-xmlreader
  - php7-xmlwriter
  - php7
  - apache2-mod_php7
web_doc_root: /srv/www/htdocs
dbserver_package: mariadb 
dbservice_name: mariadb 
fileserver_package: samba
fileservice_name: smb
web_config_file: /etc/apache2/httpd.conf
