---

- name: Install and start web service on all hosts
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: Install Webservice and PHP on CentOS
    yum:
      name: 
      - httpd
      - php
      update_cache: true
    when: ansible_distribution == 'CentOS'

  - name: Install Webservice and PHP on openSUSE Leap
    zypper:
      name:
        - w3m
        - apache2
        - apache2-mod_dnssd 
        - apache2-prefork 
        - libgc1
        - php7-ctype 
        - php7-dom 
        - php7-iconv 
        - php7-json 
        - php7-sqlite 
        - php7-tokenizer
        - php7-xmlreader 
        - php7-xmlwriter
        - php7
        - apache2-mod_php7 
      state: latest 
    when: ansible_distribution == 'openSUSE Leap'

  - name: Create phpinfo.php and put it in the right directory on CentOS
    copy:
      dest: "/var/www/html/phpinfo.php"
      content: |
        <?php phpinfo(); ?>
    when: ansible_distribution == 'CentOS'
  
  - name: Create phpinfo.php and put it in the right directory on OpenSUSE
    copy:
      dest: "/srv/www/htdocs/phpinfo.php"
      content: |
        <?php phpinfo(); ?>
    when: ansible_distribution == 'openSUSE Leap'

  - name: Start httpd
    service:
      name: httpd
      state: started
    when: ansible_distribution == 'CentOS'

  - name: Start apache2
    service:
      name: apache2
      state: started
    when: ansible_distribution == 'openSUSE Leap'

  - name: Open port 80
    firewalld:
      zone: public
      service: http
      state: enabled
      permanent: true 

