---

- name: Install and start web service on all hosts
  hosts: ~server[1:3] 
  become: true
  tasks:
  - name: Install httpd
    yum:
      name: httpd
  - name: Start httpd
    service:
      name: httpd
      state: started
  - name: Open port 80
    firewalld:
      zone: public
      service: http
      state: enabled
      permanent: true 

