---

- name: Install and start web service on all hosts
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: Update repositoy index on CentOS
    yum:
      update_cache: true
    when: ansible_distribution == 'CentOS'

  - name: Update repositoy index on openSUSE Leap
    zypper:
      name: '*'
      state: latest
    when: ansible_distribution == 'openSUSE Leap'

  - name: Install Webservice on CentOS
    yum:
      name: httpd
    when: ansible_distribution == 'CentOS'

  - name: Install Webservice on openSUSE Leap
    zypper:
      name: apache2
    when: ansible_distribution == 'openSUSE Leap'

  - name: Start httpd
    service:
      name: httpd
      state: started
    when: ansible_distribution == 'CentOS'

  - name: Start apache2
    service:
      name: apache2
      state: started
    when: ansible_distribution == 'openSUSE Leap'

  - name: Open port 80
    firewalld:
      zone: public
      service: http
      state: enabled
      permanent: true
      immediate: true 

