---

- name: Testing Pre and Post Tasks
  hosts: WebServers
  pre_tasks:
    - name: Pre Tasks
      ansible.builtin.debug:
        msg: Performing mandatory tasks  
  tasks:
    - name: Tasks
      ansible.builtin.debug:
        msg: Performing normal tasks

  post_tasks:
    - name: Post Tasks
      ansible.builtin.debug:
        msg: Performing post tasks

