---

- name: Uninstall web service on all hosts
  hosts: ~server(1|2|3) 
  become: true
  tasks:
  - name: Stop httpd
    service:
      name: httpd
      state: stopped
  - name: Uninstall httpd
    yum:
      name: httpd
      state: absent

  - name: Close port 80
    firewalld:
      zone: public
      service: http
      state: disabled
      permanent: false 
  - name: Clear firewalld logs
    shell:
      cmd: echo "" > /var/log/firewalld
